In [2]:
%matplotlib inline
import numpy as np
import pickle
import gzip


In [ ]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
v = np.reshape(v, (3,))
y = x + v 
print(y)


[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [ ]:

np.random.rand(10,1)

array([[0.33586682],
       [0.02705558],
       [0.99057818],
       [0.74842612],
       [0.6489624 ],
       [0.20927891],
       [0.81753432],
       [0.80184786],
       [0.23877362],
       [0.94842898]])

In [ ]:
for p in range(10, 0, -1):
    print(p)